# 1. Download data from https://www.kaggle.com/c/DontGetKicked . Design train/validation/test split.

Все эти разбиения были проделана в ml4, там же и была предобрабоотка пропущенных значений и все encoder.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from category_encoders import CountEncoder
from sklearn.compose import make_column_selector, ColumnTransformer
from sklearn.metrics import roc_auc_score
from tqdm import tqdm
from sklearn.tree import DecisionTreeClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [2]:
df = pd.read_csv('./data/training.csv', parse_dates=['PurchDate'])

In [3]:
df = df.sort_values('PurchDate')
df.head()

,RefId,IsBadBuy,PurchDate,Auction,VehYear,VehicleAge,Make,Model,Trim,SubModel,...,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,PRIMEUNIT,AUCGUART,BYRNO,VNZIP1,VNST,VehBCost,IsOnlineSale,WarrantyCost
32367,32389,0,2009-01-05,MANHEIM,2007,2,CHRYSLER,PACIFICA FWD 3.8L V6,Bas,4D SPORT,...,9906.0,11657.0,NaN,NaN,3453,80022,CO,6770.0,0,1389
32384,32406,0,2009-01-05,MANHEIM,2005,4,FORD,FREESTAR FWD V6 3.9L,SES,4D PASSENGER 3.9L SES,...,5801.0,6949.0,NaN,NaN,22916,80022,CO,6160.0,0,941
32385,32407,0,2009-01-05,MANHEIM,2004,5,DODGE,STRATUS 4C 2.4L I4 M,SE,4D SEDAN SE,...,4169.0,5114.0,NaN,NaN,3453,80022,CO,4250.0,0,1155
32386,32408,0,2009-01-05,MANHEIM,2006,3,CHEVROLET,TRAILBLAZER EXT 4WD,LS,4D SUV 4.2L,...,10438.0,12158.0,NaN,NaN,22916,80022,CO,8180.0,0,1703
32387,32409,0,2009-01-05,MANHEIM,2004,5,FORD,TAURUS 3.0L V6 EFI,SES,4D SEDAN SES DURATEC,...,4139.0,5351.0,NaN,NaN,22916,80022,CO,4900.0,0,825

In [4]:
train_valid_df, test_df = train_test_split(df, test_size=0.33333, shuffle=False)
train_df, valid_df = train_test_split(train_valid_df, test_size=0.5, shuffle=False)

In [5]:
X_train = train_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_train = train_df['IsBadBuy']

X_valid = valid_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_valid = valid_df['IsBadBuy']

X_test = test_df.drop(columns=['IsBadBuy', 'PurchDate'])
y_test = test_df['IsBadBuy']

In [6]:
cat_selector = make_column_selector(dtype_include=['object', 'category'])
cat_columns = cat_selector(train_df)
cat_columns

['Auction',
 'Make',
 'Model',
 'Trim',
 'SubModel',
 'Color',
 'Transmission',
 'WheelType',
 'Nationality',
 'Size',
 'TopThreeAmericanName',
 'PRIMEUNIT',
 'AUCGUART',
 'VNST']

In [7]:
def remove_nan_values(X_train, X_valid, X_test):
     # убираем 2 столбца с пропущенными значениями
    X_train.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)
    X_valid.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)
    X_test.drop(columns=['PRIMEUNIT', 'AUCGUART'], inplace=True)

    features_top = ['Trim', 'SubModel', 'Color', 'Transmission', 'WheelTypeID', 'WheelType']
    features_mean = ['MMRAcquisitionAuctionAveragePrice', 'MMRAcquisitionAuctionCleanPrice',
       'MMRAcquisitionRetailAveragePrice', 'MMRAcquisitonRetailCleanPrice',
       'MMRCurrentAuctionAveragePrice', 'MMRCurrentAuctionCleanPrice',
       'MMRCurrentRetailAveragePrice', 'MMRCurrentRetailCleanPrice']
    
    for feature in features_top:
        base = X_train[feature].value_counts().iloc[0]

        X_train.loc[X_train[feature].isna(), feature] = base
        X_valid.loc[X_valid[feature].isna(), feature] = base
        X_test.loc[X_test[feature].isna(), feature] = base

    for feature in features_mean:
        base = X_train[feature].mean()

        X_train.loc[X_train[feature].isna(), feature] = base
        X_valid.loc[X_valid[feature].isna(), feature] = base
        X_test.loc[X_test[feature].isna(), feature] = base
    
    return X_train, X_valid, X_test

In [8]:
X_train, X_valid, X_test = remove_nan_values(X_train, X_valid, X_test)

In [9]:
y_valid.drop(index=X_valid[X_valid['Size'].isna()].index, inplace=True)
X_valid.drop(index=X_valid[X_valid['Size'].isna()].index, inplace=True)
X_valid.isna().sum().sum()

np.int64(0)

In [10]:
categorical_columns = ['Auction', 'Make', 'Model', 'Trim', 'SubModel', 'Color', 'Transmission', 'WheelType', 'Nationality', 'Size', 'TopThreeAmericanName', 'VNST']

In [11]:
for col in categorical_columns:
    X_train[col] = X_train[col].astype(str)
    X_valid[col] = X_valid[col].astype(str)
    X_test[col] = X_test[col].astype(str)

In [12]:
numeric_columns = [column for column in X_train.columns if column not in categorical_columns]
numeric_columns

['RefId',
 'VehYear',
 'VehicleAge',
 'WheelTypeID',
 'VehOdo',
 'MMRAcquisitionAuctionAveragePrice',
 'MMRAcquisitionAuctionCleanPrice',
 'MMRAcquisitionRetailAveragePrice',
 'MMRAcquisitonRetailCleanPrice',
 'MMRCurrentAuctionAveragePrice',
 'MMRCurrentAuctionCleanPrice',
 'MMRCurrentRetailAveragePrice',
 'MMRCurrentRetailCleanPrice',
 'BYRNO',
 'VNZIP1',
 'VehBCost',
 'IsOnlineSale',
 'WarrantyCost']

In [13]:
X_valid.loc[X_valid.Transmission == 'Manual', 'Transmission'] = 'MANUAL'

In [14]:
categorical_columns.remove('Make')
categorical_columns.remove('Model')
categorical_columns.remove('Trim')
categorical_columns.remove('SubModel')
categorical_columns.remove('VNST')

transformers = [
    ('num', 'passthrough', numeric_columns),
    ('cat', OneHotEncoder(), categorical_columns),
    ('count_scaled', CountEncoder(), ['Make', 'Model', 'Trim', 'SubModel', 'VNST'])
]

ct = ColumnTransformer(transformers, remainder='drop')
X_train_transform = ct.fit_transform(X_train)
X_valid_transform = ct.transform(X_valid)
X_test_transform = ct.transform(X_test)

In [15]:
pd.DataFrame(X_train_transform, columns=ct.get_feature_names_out())

,num__RefId,num__VehYear,num__VehicleAge,num__WheelTypeID,num__VehOdo,num__MMRAcquisitionAuctionAveragePrice,num__MMRAcquisitionAuctionCleanPrice,num__MMRAcquisitionRetailAveragePrice,num__MMRAcquisitonRetailCleanPrice,num__MMRCurrentAuctionAveragePrice,...,cat__Size_VAN,cat__TopThreeAmericanName_CHRYSLER,cat__TopThreeAmericanName_FORD,cat__TopThreeAmericanName_GM,cat__TopThreeAmericanName_OTHER,count_scaled__Make,count_scaled__Model,count_scaled__Trim,count_scaled__SubModel,count_scaled__VNST
0,32389.0,2007.0,2.0,2.0,78541.0,7261.0,8857.0,8342.0,10066.0,8709.0,...,0.0,1.0,0.0,0.0,0.0,2774.0,99.0,4540.0,284.0,2016.0
1,32406.0,2005.0,4.0,1.0,37676.0,4409.0,5734.0,5262.0,6693.0,4908.0,...,1.0,0.0,1.0,0.0,0.0,4264.0,309.0,265.0,46.0,2016.0
2,32407.0,2004.0,5.0,2.0,71680.0,3098.0,4061.0,3846.0,4886.0,3397.0,...,0.0,1.0,0.0,0.0,0.0,4784.0,250.0,3432.0,1427.0,2016.0
3,32408.0,2006.0,3.0,1.0,69456.0,8530.0,9883.0,9712.0,11174.0,9202.0,...,0.0,0.0,0.0,1.0,0.0,5659.0,55.0,2988.0,177.0,2016.0
4,32409.0,2004.0,5.0,1.0,66530.0,3094.0,4230.0,3842.0,5068.0,3369.0,...,0.0,0.0,1.0,0.0,0.0,4264.0,955.0,265.0,58.0,2016.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24322,56894.0,2005.0,4.0,2.0,70531.0,3150.0,4011.0,3902.0,4832.0,3148.0,...,0.0,0.0,0.0,1.0,0.0,5659.0,68.0,2988.0,4903.0,2554.0
24323,56893.0,2008.0,1.0,2.0,64301.0,8607.0,9350.0,9796.0,10598.0,7965.0,...,0.0,1.0,0.0,0.0,0.0,4784.0,276.0,3432.0,4903.0,2554.0
24324,56892.0,2008.0,1.0,2.0,64524.0,8607.0,9350.0,9796.0,10598.0,8568.0,...,0.0,1.0,0.0,0.0,0.0,4784.0,276.0,3432.0,4903.0,2554.0
24325,15848.0,2006.0,3.0,2.0,78217.0,8702.0,10517.0,9898.0,11858.0,7590.0,...,0.0,0.0,0.0,0.0,1.0,198.0,23.0,69.0,61.0,4562.0
24326,15849.0,2006.0,3.0,2.0,67097.0,6508.0,8268.0,7529.0,9429.0,6470.0,...,1.0,1.0,0.0,0.0,0.0,4784.0,522.0,4540.0,517.0,4562.0

Все пропущенные значения предобработаны и применены енкодеры для категориальных признаков. Нормализация не производилась, так как для моделей с деревьями она не нужна.

# 2. Create a Python class for DEcision Tree Classifier and Decosoin Tree Regressor (MSE loss)

класс Node - узла дерева, который хранит данные, условия разделения и указатели на правого и левого потомков

In [16]:
class Node:
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.left_child = None
        self.right_child = None
        self.split_feature = None
        self.split_value = None

    def set_left_child(self, pointer):
        self.left_child = pointer

    def set_right_child(self, pointer):
        self.right_child = pointer

    def get_Gini(self):
        probability_y_0 = (self.y == 0).sum() / len(self.y)
        probability_y_1 = 1 - probability_y_0

        gini_impurity = probability_y_0*(1 - probability_y_0) + probability_y_1*(1 - probability_y_1)

        return gini_impurity
    
    def get_standard_devation(self):
        return np.std(self.y)

    def get_X(self):
        return self.X

    def get_y(self):
        return self.y

In [17]:
len(X_train_transform)

24327

класс DecisionTreeClassifier - то есть строить деревья по информативности gini и решает задачу бинароной классификации

In [18]:
class myDesicionTreeClassifier:
    def __init__(self, max_depth=10, min_samples_split=2, max_features=None, random_state=21):
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.max_features = max_features
        self.random_state = random_state

    def _compute_gini(self, y):
         if len(y) == 0: return 0
         P = (y == 1).sum() / len(y)
         return 2 * P * (1 - P)

    def find_best_split(self, node):
        X = node.get_X()
        y = node.get_y()

        if node.get_Gini() == 0:
            return None, None

        optimal_feature = None
        optimal_value = None
        best_score = 0

        np.random.seed(self.random_state)

        if self.max_features is not None:
            feature_indices = np.random.choice(X.shape[1], self.max_features, replace=False)
        else:
            feature_indices = range(X.shape[1])

        for i in feature_indices:
            feature_value = X[:, i]
            n_unique = len(np.unique(feature_value))

            if n_unique > 100:
                percentiles = np.linspace(0, 100, 100)
                candidate_values = np.percentile(feature_value, percentiles)
            else:
                candidate_values = np.unique(feature_value)


            for value in candidate_values:
                left_mask = X[:,i] <= value
                right_mask = ~left_mask

                y_left = y[left_mask]
                y_right = y[right_mask]
                
                if (len(y_left) < self.min_samples_split) or (len(y_right) < self.min_samples_split):
                     continue

                left_gini = self._compute_gini(y_left)
                right_gini = self._compute_gini(y_right)

                score = len(X) * node.get_Gini() - len(y_left) * left_gini - len(y_right) * right_gini

                if score > best_score:
                    best_score = score
                    optimal_feature = i
                    optimal_value = value
        
        return optimal_feature, optimal_value
    
    def prune_tree(self, node):
        node.X = None
        
        if node.left_child:
            self.prune_tree(node.left_child)
        if node.right_child:
            self.prune_tree(node.right_child)
        
    def fit(self, X_train, y_train):
        self.root = Node(X_train, y_train)
        self.make_split(self.root, 2)

        self.prune_tree(self.root)
        

    def make_split(self, current_node, level):
        if level >= self.max_depth:
            return
        
        if len(current_node.y) < self.min_samples_split:
            return
         
        split_feature, split_value = self.find_best_split(current_node)

        if split_feature is not None:
            left_mask = current_node.X[:,split_feature] <= split_value
            right_mask = current_node.X[:,split_feature] > split_value

            left_child = Node(current_node.X[left_mask], current_node.y[left_mask])
            right_child = Node(current_node.X[right_mask], current_node.y[right_mask])

            current_node.split_feature = split_feature
            current_node.split_value = split_value

            current_node.set_left_child(left_child)
            current_node.set_right_child(right_child)

            self.make_split(current_node.left_child, level + 1)
            self.make_split(current_node.right_child, level + 1)

    def get_probability(self, sample, current_node):
        if current_node.split_feature is None:
            return np.mean(current_node.y)
        
        if sample[current_node.split_feature] <= current_node.split_value:
            return self.get_probability(sample, current_node.left_child)
        else:
            return self.get_probability(sample, current_node.right_child)

    
    def predict_proba(self, X):
        answer = []
        for sample in X:
            answer.append(self.get_probability(sample, self.root))
        
        return np.array(answer)

    def predict(self, X, threshold=0.5):
        predict = (self.predict_proba(X) > 0.5).astype(int)
        return predict

In [19]:
class myDesicionTreeRegression:
    def __init__(self, max_depth=10, min_samples_split=2, max_features=20, random_state=21):
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.max_features = max_features
        self.random_state = random_state

    def _compute_standard_devation(self, y):
        if len(y) == 0: return 0
        return np.std(y)

    def find_best_split(self, node):
        X = node.get_X()
        y = node.get_y()

        if node.get_standard_devation() == 0:
            return None, None

        optimal_feature = None
        optimal_value = None
        best_score = 0

        np.random.seed(self.random_state)
        indices = np.arange(X.shape[1])
        np.random.shuffle(indices)

        for i in indices[:self.max_features]:
            feature_value = X[:, i]
            n_unique = len(np.unique(feature_value))

            if n_unique > 100:
                percentiles = np.linspace(0, 100, 100)
                candidate_values = np.percentile(feature_value, percentiles)
            else:
                candidate_values = np.unique(feature_value)

            for value in candidate_values:
                left_mask = X[:,i] <= value
                right_mask = ~left_mask

                y_left = y[left_mask]
                y_right = y[right_mask]
                
                if (len(y_left) < self.min_samples_split) or (len(y_right) < self.min_samples_split):
                     continue

                left_standard_devation = self._compute_standard_devation(y_left)
                right_standard_devation = self._compute_standard_devation(y_right)

                score = len(X) * node.get_standard_devation() - len(y_left) * left_standard_devation - len(y_right) * right_standard_devation

                if score > best_score:
                    best_score = score
                    optimal_feature = i
                    optimal_value = value
        
        return optimal_feature, optimal_value
        
    def prune_tree(self, node):
        node.X = None
        
        if node.left_child:
            self.prune_tree(node.left_child)
        if node.right_child:
            self.prune_tree(node.right_child)
        
    def fit(self, X_train, y_train):
        self.root = Node(X_train, y_train)
        self.make_split(self.root, 2)

        self.prune_tree(self.root)
        

    def make_split(self, current_node, level):
        if level >= self.max_depth:
            return
        
        if len(current_node.y) < self.min_samples_split:
            return
         
        split_feature, split_value = self.find_best_split(current_node)

        if split_feature is not None:
            left_mask = current_node.X[:,split_feature] <= split_value
            right_mask = current_node.X[:,split_feature] > split_value

            left_child = Node(current_node.X[left_mask], current_node.y[left_mask])
            right_child = Node(current_node.X[right_mask], current_node.y[right_mask])

            current_node.split_feature = split_feature
            current_node.split_value = split_value

            current_node.set_left_child(left_child)
            current_node.set_right_child(right_child)

            self.make_split(current_node.left_child, level + 1)
            self.make_split(current_node.right_child, level + 1)

    def predict(self, X):
        predictions = []
        for sample in X:
            node = self.root
            while node.left_child or node.right_child:
                if sample[node.split_feature] <= node.split_value:
                    node = node.left_child
                else:
                    node = node.right_child
            predictions.append(np.mean(node.y))
        return np.array(predictions)

ExtraRandomizedTree - класс, где логика как для классификации, только мы не ищем раздедение не по всем признакам, а только по рандомной части из них, и при этом мы не перебираем все возможные значения для разделения, или не берём квантили, а берем некоторое рандомно количество разлиичным примеров, и уже среди них ищем лучшее разделение.

In [20]:
class myExtraRandomizedTree:
    def __init__(self, max_depth=10, min_samples_split=2, max_features=20, random_state=21):
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.max_features = max_features
        self.random_state = random_state

    def _compute_gini(self, y):
         if len(y) == 0: return 0
         P = (y == 1).sum() / len(y)
         return 2 * P * (1 - P)

    def find_best_split(self, node):
        X = node.get_X()
        y = node.get_y()

        if node.get_Gini() == 0:
            return None, None

        optimal_feature = None
        optimal_value = None
        best_score = 0

        np.random.seed(self.random_state)
        indices = np.arange(X.shape[1])
        np.random.shuffle(indices)

        for i in indices[:self.max_features]:
            feature_value = X[:, i]
            n_unique = len(np.unique(feature_value))

            if n_unique > 20:
                candidate_values = np.random.choice(feature_value, size=20, replace=False)
            else:
                candidate_values = np.random.choice(feature_value, size=n_unique // 2, replace=False)
            
            for value in candidate_values:
                left_mask = X[:,i] <= value
                right_mask = ~left_mask

                y_left = y[left_mask]
                y_right = y[right_mask]
                
                if (len(y_left) < self.min_samples_split) or (len(y_right) < self.min_samples_split):
                     continue

                left_gini = self._compute_gini(y_left)
                right_gini = self._compute_gini(y_right)

                score = len(X) * node.get_Gini() - len(y_left) * left_gini - len(y_right) * right_gini

                if score > best_score:
                    best_score = score
                    optimal_feature = i
                    optimal_value = value
        
        return optimal_feature, optimal_value
        
    def prune_tree(self, node):
        node.X = None
        
        if node.left_child:
            self.prune_tree(node.left_child)
        if node.right_child:
            self.prune_tree(node.right_child)
        
    def fit(self, X_train, y_train):
        self.root = Node(X_train, y_train)
        self.make_split(self.root, 2)

        self.prune_tree(self.root)
        

    def make_split(self, current_node, level):
        if level >= self.max_depth:
            return
        
        if len(current_node.y) < self.min_samples_split:
            return
         
        split_feature, split_value = self.find_best_split(current_node)

        if split_feature is not None:
            left_mask = current_node.X[:,split_feature] <= split_value
            right_mask = current_node.X[:,split_feature] > split_value

            left_child = Node(current_node.X[left_mask], current_node.y[left_mask])
            right_child = Node(current_node.X[right_mask], current_node.y[right_mask])

            current_node.split_feature = split_feature
            current_node.split_value = split_value

            current_node.set_left_child(left_child)
            current_node.set_right_child(right_child)

            self.make_split(current_node.left_child, level + 1)
            self.make_split(current_node.right_child, level + 1)

    def get_probability(self, sample, current_node):
        if current_node.split_feature is None:
            return np.mean(current_node.y)
        
        if sample[current_node.split_feature] <= current_node.split_value:
            return self.get_probability(sample, current_node.left_child)
        else:
            return self.get_probability(sample, current_node.right_child)

    
    def predict_proba(self, X):
        answer = [self.get_probability(sample, self.root) for sample in X]
        
        return np.array(answer)

    def predict(self, X, threshold=0.5):
        predict = (self.predict_proba(X) > 0.5).astype(int)
        return np.array(predict)

# 3. Wuth your DicisionTree module, you must obtain a Gini score of at least 0.1 on the validation dataset.

In [21]:
def gini_score(y_true, y_pred):
    return 2 * roc_auc_score(y_true, y_pred) - 1

In [22]:
my_tree_classifier = myDesicionTreeClassifier(max_depth=5)
my_tree_classifier.fit(X_train_transform, y_train)

In [23]:
my_tree_gini = gini_score(y_valid, my_tree_classifier.predict_proba(X_valid_transform))

print(f'My Gini for myDecisionTreeClassifier:  {my_tree_gini}')

My Gini for myDecisionTreeClassifier:  0.4258553278712276

# 4. Use sklearn's DecisionTreeClassifier and checl ots perfomance on the validation dataset. Is it better then your module? If so, why ?

In [24]:
tree_classifier = DecisionTreeClassifier(max_depth=5)
tree_classifier.fit(X_train_transform, y_train)
tree_gini = gini_score(y_valid, tree_classifier.predict_proba(X_valid_transform)[:,1])

In [25]:
print(f'Gini for sklearn decisionTreeClassifier:  {tree_gini}')
print(f'My Gini for myDecisionTreeClassifier:  {my_tree_gini}')

Gini for sklearn decisionTreeClassifier:  0.4524264510073599
My Gini for myDecisionTreeClassifier:  0.4258553278712276

У sklearn DecisionTreeClassifer значения gini score лучше, чем моя реализация. Скорее всего это связано с более оптимизирвоанными и лучшими поисками разделения, а также большим количество параметров, для обучения. То есть моя модель неплохая, но в сравнении намного меньше гибкости параметров. 

Также при обучении в моей модели, если уникальных значений более 100, то я брал квантили, а не перебирал все занчения, так как перебирать полностью слишком долго. А sklearn за счёт более оптимизированных методов может находить разделения лучше моих.

# 5. Implement the RandomForestClassifier  and check its perfomance. You have to improve the result of a single tree and get at least 0.15 Gini score on validation dataset. Be able to set a fixed random seed.

In [26]:
class myRandomForestClassifier:
    def __init__(self, n_estimators=100, random_state=21, max_depth=15, max_features='sqrt'):
        self.n_estimators = n_estimators
        self.random_state = random_state
        self.max_depth = max_depth
        self.max_features = max_features
        self.trees = []
    
    def fit(self, X, y):
        if self.max_features == 'sqrt':
            max_features = int(np.sqrt(X.shape[1]))
        else:
            raise print(f'Unknown value of parameter max_features:  {self.max_features}???')
        
        np.random.seed(self.random_state)
        tree_random_state = self.random_state
        indices = np.arange(len(X))
        yy = np.array(y)
        
        for i in tqdm(range(self.n_estimators), desc=f'Fitting  forest'):

            tree = myDesicionTreeClassifier(max_depth=self.max_depth, max_features=max_features, random_state=tree_random_state)
            tree_random_state += 1
        
            subsampling_indices = np.random.choice(indices, size=len(X), replace=True)

            X_subsampling = X[subsampling_indices]
            y_subsampling = yy[subsampling_indices]

            tree.fit(X_subsampling, y_subsampling)

            self.trees.append(tree)
    
    def predict_proba(self, X):
        votes = [tree.predict_proba(X) for tree in self.trees]

        return np.mean(votes, axis=0)
    
    def predict(self, X, threshold=0.5):
        predictions = (self.predict_proba(X) > threshold).astype(int)

        return np.array(predictions)

In [27]:
my_forest = myRandomForestClassifier(max_depth=10)
my_forest.fit(X_train_transform, y_train)

Fitting  forest: 100%|██████████| 100/100 [00:58<00:00,  1.72it/s]

In [28]:
forest_gini_ = gini_score(y_valid, my_forest.predict_proba(X_valid_transform))

print(f'Gini score for my RandomForestClassifier:  {forest_gini_}')

Gini score for my RandomForestClassifier:  0.4554602354851165

# 6. Use your DecisionTree design class for GBDT classfier. 

This class must have max_depth, number_of_trees and max_features attributes.

You must compute the gradient of the binary cross-entropy loss function and implement incremential learning: train the next tree using the results of the previous trees.

Формула антиградиента для binary cross_entropy loss function: y/p - (1-y)/(1-p)

In [29]:
class myGBDT:
    def __init__(self, max_depth=3, number_of_trees=100, max_features=9, random_state=21, learning_rate=0.1):
        self.max_depth=max_depth
        self.number_of_trees=number_of_trees
        self.max_features=max_features
        self.random_state=random_state
        self.learning_rate = learning_rate
        self.trees = []

    def fit(self, X, y):
        self.base_predict = np.mean(y)
        current_pred = np.full(len(y), self.base_predict)

        for i in tqdm(range(self.number_of_trees), desc='Fitting GBDT'):
            tree = myDesicionTreeRegression(max_depth=self.max_depth, max_features=self.max_features, random_state=self.random_state + i)
            
            target = y/current_pred - (1-y) / (1-current_pred)
            tree.fit(X, target)

            tree_pred = tree.predict(X)
            current_pred += self.learning_rate * tree_pred
            current_pred = np.clip(current_pred, 1e-15, 1-1e-15)

            self.trees.append(tree)
            
    def predict_proba(self, X):
        predict = np.full(X.shape[0], self.base_predict)
        
        tree_preds = [tree.predict(X) for tree in self.trees]

        total_correction = np.sum(tree_preds, axis=0) * self.learning_rate
    
        return predict + total_correction
    
    def predict(self, X, threshold=0.5):
        predictions = (self.predict_proba(X) >= threshold).astype(int)

        return predictions

In [30]:
my_gbdt = myGBDT(learning_rate=0.01)
my_gbdt.fit(X_train_transform, y_train)

Fitting GBDT: 100%|██████████| 100/100 [01:10<00:00,  1.43it/s]

In [31]:
gbdt_gini = gini_score(y_valid, my_gbdt.predict_proba(X_valid_transform))

print(f'Gini score for my GBDT classifier:  {gbdt_gini}')

Gini score for my GBDT classifier:  0.4610974943849675

# 7. Use LightGBM, Catboost and XGBoost for fitting on a traning set and prediction on a validation set.

Rewiew the documentation of the libraries and fine_tune the algorithms for the task. Note key differences between each implementation. Analyze special features of each algorithm (how does 'categorical feature' work in Catboost, what is DART mode in XGBoost)? Which GBDT model gives the best result ? Can you explain why?

### CatBoost

Алгоритм, разработанный Яндексом в 2017 году. Это метод градиентного бустинга на решающих деревевьях. Особенности:
- может обрабатывать категриальные признакки. То есть в него встроенные инструменты обработки категориальных признаков, что позволяет не заниматься самостоятельной предобработкой данных. Данные предобрабатываются по разным критериям и весьма эффективно. Можно просто указать параметр cat_features, в котором передать какие признаки являются категорильными, чтобы аглоритм их обработал.
- способ построения деревьев отличается от других методов, а именно строятся бинарные сбалансированнные деревеься, и также на каждом уровне дерева, во всех узлах этого уровня одинаковый критерий деления. Данный способ построения деревьев минимизирует переобучение. То есть не только за счёт ограничения глубины дерева или других способ, а своей архитектурой метода.
- процесс обучения и предсказания весьма быстрый. Конечно для LightGBM быстрее обучение, но это и очевидно, так как сам метод облегчённый.
- имеет множество встроенных методов, которые упрощяют работу, помимо втроенных способ обработка категорильаных признаков, модель сама моежет побирать занчения learning_rate по данным
- также может работать с текстовыми признаками (параметр test_features метода fit)

In [32]:
cat_columns = cat_selector(X_train)
cat_columns

['Auction',
 'Make',
 'Model',
 'Trim',
 'SubModel',
 'Color',
 'Transmission',
 'WheelType',
 'Nationality',
 'Size',
 'TopThreeAmericanName',
 'VNST']

In [33]:
model_CatBoost = CatBoostClassifier(random_state=21)
model_CatBoost.fit(X_train, y_train, cat_features=cat_columns)

Learning rate set to 0.040253
0:	learn: 0.6554291	total: 192ms	remaining: 3m 12s
1:	learn: 0.6215789	total: 237ms	remaining: 1m 58s
2:	learn: 0.5922339	total: 263ms	remaining: 1m 27s
3:	learn: 0.5638864	total: 304ms	remaining: 1m 15s
4:	learn: 0.5377464	total: 349ms	remaining: 1m 9s
5:	learn: 0.5154086	total: 392ms	remaining: 1m 4s
6:	learn: 0.4948314	total: 434ms	remaining: 1m 1s
7:	learn: 0.4774266	total: 477ms	remaining: 59.1s
8:	learn: 0.4617348	total: 506ms	remaining: 55.8s
9:	learn: 0.4471563	total: 539ms	remaining: 53.4s
10:	learn: 0.4343732	total: 568ms	remaining: 51s
11:	learn: 0.4219472	total: 607ms	remaining: 50s
12:	learn: 0.4098117	total: 649ms	remaining: 49.3s
13:	learn: 0.3993896	total: 693ms	remaining: 48.8s
14:	learn: 0.3901518	total: 729ms	remaining: 47.9s
15:	learn: 0.3819824	total: 773ms	remaining: 47.5s
16:	learn: 0.3752290	total: 789ms	remaining: 45.6s
17:	learn: 0.3683712	total: 831ms	remaining: 45.4s
18:	learn: 0.3617401	total: 873ms	remaining: 45.1s
19:	learn: 0.3567522	total: 892ms	remaining: 43.7s
20:	learn: 0.3515797	total: 935ms	remaining: 43.6s
21:	learn: 0.3468294	total: 977ms	remaining: 43.4s
22:	learn: 0.3425243	total: 1.02s	remaining: 43.4s
23:	learn: 0.3389208	total: 1.06s	remaining: 43s
24:	learn: 0.3352931	total: 1.1s	remaining: 42.8s
25:	learn: 0.3325398	total: 1.11s	remaining: 41.8s
26:	learn: 0.3293023	total: 1.16s	remaining: 41.8s
27:	learn: 0.3266905	total: 1.19s	remaining: 41.2s
28:	learn: 0.3243795	total: 1.23s	remaining: 41.2s
29:	learn: 0.3220165	total: 1.26s	remaining: 40.9s
30:	learn: 0.3194759	total: 1.31s	remaining: 40.9s
31:	learn: 0.3174862	total: 1.39s	remaining: 41.9s
32:	learn: 0.3155066	total: 1.43s	remaining: 41.8s
33:	learn: 0.3139303	total: 1.47s	remaining: 41.8s
34:	learn: 0.3122440	total: 1.51s	remaining: 41.7s
35:	learn: 0.3109351	total: 1.56s	remaining: 41.7s
36:	learn: 0.3096010	total: 1.6s	remaining: 41.6s
37:	learn: 0.3082059	total: 1.64s	remaining: 41.6s
38:	learn: 0.3070545	total: 1.69s	remaining: 41.6s
39:	learn: 0.3059511	total: 1.73s	remaining: 41.6s
40:	learn: 0.3048095	total: 1.77s	remaining: 41.5s
41:	learn: 0.3038956	total: 1.81s	remaining: 41.4s
42:	learn: 0.3030444	total: 1.85s	remaining: 41.3s
43:	learn: 0.3022200	total: 1.9s	remaining: 41.3s
44:	learn: 0.3014208	total: 1.95s	remaining: 41.3s
45:	learn: 0.3007280	total: 1.99s	remaining: 41.3s
46:	learn: 0.3000592	total: 2.04s	remaining: 41.3s
47:	learn: 0.2994840	total: 2.08s	remaining: 41.2s
48:	learn: 0.2991231	total: 2.1s	remaining: 40.7s
49:	learn: 0.2987129	total: 2.13s	remaining: 40.5s
50:	learn: 0.2983144	total: 2.15s	remaining: 40s
51:	learn: 0.2977724	total: 2.19s	remaining: 40s
52:	learn: 0.2973723	total: 2.23s	remaining: 39.9s
53:	learn: 0.2966881	total: 2.27s	remaining: 39.9s
54:	learn: 0.2963569	total: 2.31s	remaining: 39.8s
55:	learn: 0.2957970	total: 2.36s	remaining: 39.8s
56:	learn: 0.2954513	total: 2.4s	remaining: 39.8s
57:	learn: 0.2947945	total: 2.44s	remaining: 39.7s
58:	learn: 0.2943435	total: 2.49s	remaining: 39.7s
59:	learn: 0.2940816	total: 2.53s	remaining: 39.7s
60:	learn: 0.2937147	total: 2.57s	remaining: 39.6s
61:	learn: 0.2934126	total: 2.61s	remaining: 39.5s
62:	learn: 0.2930929	total: 2.65s	remaining: 39.5s
63:	learn: 0.2928395	total: 2.7s	remaining: 39.4s
64:	learn: 0.2924498	total: 2.74s	remaining: 39.4s
65:	learn: 0.2921358	total: 2.78s	remaining: 39.3s
66:	learn: 0.2917639	total: 2.83s	remaining: 39.4s
67:	learn: 0.2917217	total: 2.84s	remaining: 38.9s
68:	learn: 0.2915701	total: 2.88s	remaining: 38.9s
69:	learn: 0.2912981	total: 2.92s	remaining: 38.8s
70:	learn: 0.2909624	total: 2.97s	remaining: 38.8s
71:	learn: 0.2908031	total: 3.01s	remaining: 38.8s
72:	learn: 0.2905174	total: 3.05s	remaining: 38.8s
73:	learn: 0.2903092	total: 3.09s	remaining: 38.7s
74:	learn: 0.2902131	total: 3.14s	remaining: 38.7s
75:	learn: 0.2899764	total: 3.18s	remaining: 38.7s
76:	learn: 0.2897517	total: 3.23s	remaining: 38.7s
77:	learn: 0.2895306	total: 3.27s	remaining: 38.7s
78:	learn: 0.2892582	total: 3.32s	remaining: 38.7s
79:	learn: 0.2891692	total: 3.36s	remaining: 38.6s
80:	learn: 0.2889619	total: 3.4s	remaining: 38.6s
81:	learn: 0.2888418	total: 3.43s	remaining: 38.4s
82:	learn: 0.2886942	total: 3.47s	remaining: 38.4s
83:	learn: 0.2885345	total: 3.51s	remaining: 38.3s
84:	learn: 0.2883756	total: 3.55s	remaining: 38.3s
85:	learn: 0.2882453	total: 3.59s	remaining: 38.2s
86:	learn: 0.2881765	total: 3.62s	remaining: 38s
87:	learn: 0.2879760	total: 3.66s	remaining: 38s
88:	learn: 0.2877839	total: 3.71s	remaining: 37.9s
89:	learn: 0.2876734	total: 3.75s	remaining: 37.9s
90:	learn: 0.2875192	total: 3.79s	remaining: 37.9s
91:	learn: 0.2873757	total: 3.84s	remaining: 37.9s
92:	learn: 0.2871775	total: 3.88s	remaining: 37.8s
93:	learn: 0.2870192	total: 3.92s	remaining: 37.8s
94:	learn: 0.2868555	total: 3.96s	remaining: 37.7s
95:	learn: 0.2867725	total: 4s	remaining: 37.7s
96:	learn: 0.2866123	total: 4.04s	remaining: 37.6s
97:	learn: 0.2864799	total: 4.1s	remaining: 37.7s
98:	learn: 0.2862606	total: 4.14s	remaining: 37.7s
99:	learn: 0.2861676	total: 4.19s	remaining: 37.7s
100:	learn: 0.2860467	total: 4.23s	remaining: 37.7s
101:	learn: 0.2859015	total: 4.28s	remaining: 37.7s
102:	learn: 0.2857305	total: 4.32s	remaining: 37.6s
103:	learn: 0.2855898	total: 4.36s	remaining: 37.6s
104:	learn: 0.2854939	total: 4.4s	remaining: 37.5s
105:	learn: 0.2853664	total: 4.44s	remaining: 37.5s
106:	learn: 0.2853101	total: 4.49s	remaining: 37.5s
107:	learn: 0.2852327	total: 4.54s	remaining: 37.5s
108:	learn: 0.2851094	total: 4.58s	remaining: 37.4s
109:	learn: 0.2850201	total: 4.63s	remaining: 37.4s
110:	learn: 0.2849012	total: 4.67s	remaining: 37.4s
111:	learn: 0.2848522	total: 4.7s	remaining: 37.3s
112:	learn: 0.2847393	total: 4.75s	remaining: 37.3s
113:	learn: 0.2845710	total: 4.79s	remaining: 37.2s
114:	learn: 0.2844677	total: 4.84s	remaining: 37.2s
115:	learn: 0.2844073	total: 4.88s	remaining: 37.2s
116:	learn: 0.2842683	total: 4.92s	remaining: 37.2s
117:	learn: 0.2841922	total: 4.96s	remaining: 37.1s
118:	learn: 0.2839439	total: 5.01s	remaining: 37.1s
119:	learn: 0.2838450	total: 5.05s	remaining: 37s
120:	learn: 0.2837504	total: 5.09s	remaining: 37s
121:	learn: 0.2836855	total: 5.13s	remaining: 36.9s
122:	learn: 0.2836166	total: 5.17s	remaining: 36.9s
123:	learn: 0.2835687	total: 5.21s	remaining: 36.8s
124:	learn: 0.2834820	total: 5.26s	remaining: 36.8s
125:	learn: 0.2833901	total: 5.29s	remaining: 36.7s
126:	learn: 0.2833141	total: 5.34s	remaining: 36.7s
127:	learn: 0.2832091	total: 5.38s	remaining: 36.7s
128:	learn: 0.2830574	total: 5.43s	remaining: 36.6s
129:	learn: 0.2829929	total: 5.47s	remaining: 36.6s
130:	learn: 0.2829805	total: 5.5s	remaining: 36.5s
131:	learn: 0.2829805	total: 5.51s	remaining: 36.3s
132:	learn: 0.2829263	total: 5.56s	remaining: 36.2s
133:	learn: 0.2828035	total: 5.6s	remaining: 36.2s
134:	learn: 0.2826141	total: 5.64s	remaining: 36.2s
135:	learn: 0.2825532	total: 5.69s	remaining: 36.1s
136:	learn: 0.2823937	total: 5.73s	remaining: 36.1s
137:	learn: 0.2823832	total: 5.75s	remaining: 35.9s
138:	learn: 0.2823355	total: 5.79s	remaining: 35.9s
139:	learn: 0.2822624	total: 5.83s	remaining: 35.8s
140:	learn: 0.2821504	total: 5.88s	remaining: 35.8s
141:	learn: 0.2820321	total: 5.92s	remaining: 35.8s
142:	learn: 0.2819643	total: 5.98s	remaining: 35.8s
143:	learn: 0.2818485	total: 6.02s	remaining: 35.8s
144:	learn: 0.2817548	total: 6.07s	remaining: 35.8s
145:	learn: 0.2817105	total: 6.11s	remaining: 35.7s
146:	learn: 0.2816737	total: 6.16s	remaining: 35.8s
147:	learn: 0.2816506	total: 6.19s	remaining: 35.6s
148:	learn: 0.2816185	total: 6.23s	remaining: 35.6s
149:	learn: 0.2815046	total: 6.27s	remaining: 35.5s
150:	learn: 0.2814795	total: 6.3s	remaining: 35.4s
151:	learn: 0.2814379	total: 6.34s	remaining: 35.4s
152:	learn: 0.2813936	total: 6.38s	remaining: 35.3s
153:	learn: 0.2813376	total: 6.42s	remaining: 35.3s
154:	learn: 0.2812770	total: 6.47s	remaining: 35.3s
155:	learn: 0.2811790	total: 6.51s	remaining: 35.2s
156:	learn: 0.2811118	total: 6.55s	remaining: 35.2s
157:	learn: 0.2810432	total: 6.59s	remaining: 35.1s
158:	learn: 0.2808931	total: 6.63s	remaining: 35.1s
159:	learn: 0.2807939	total: 6.68s	remaining: 35.1s
160:	learn: 0.2806098	total: 6.72s	remaining: 35s
161:	learn: 0.2805570	total: 6.77s	remaining: 35s
162:	learn: 0.2804909	total: 6.81s	remaining: 35s
163:	learn: 0.2804362	total: 6.86s	remaining: 34.9s
164:	learn: 0.2803312	total: 6.9s	remaining: 34.9s
165:	learn: 0.2803203	total: 6.92s	remaining: 34.8s
166:	learn: 0.2802183	total: 6.96s	remaining: 34.7s
167:	learn: 0.2801286	total: 7s	remaining: 34.7s
168:	learn: 0.2801251	total: 7.03s	remaining: 34.6s
169:	learn: 0.2800310	total: 7.07s	remaining: 34.5s
170:	learn: 0.2799830	total: 7.11s	remaining: 34.5s
171:	learn: 0.2798892	total: 7.16s	remaining: 34.4s
172:	learn: 0.2798319	total: 7.2s	remaining: 34.4s
173:	learn: 0.2797438	total: 7.24s	remaining: 34.4s
174:	learn: 0.2796599	total: 7.28s	remaining: 34.3s
175:	learn: 0.2796099	total: 7.32s	remaining: 34.3s
176:	learn: 0.2795480	total: 7.36s	remaining: 34.2s
177:	learn: 0.2794662	total: 7.4s	remaining: 34.2s
178:	learn: 0.2794234	total: 7.45s	remaining: 34.2s
179:	learn: 0.2793506	total: 7.5s	remaining: 34.2s
180:	learn: 0.2792649	total: 7.54s	remaining: 34.1s
181:	learn: 0.2791894	total: 7.59s	remaining: 34.1s
182:	learn: 0.2791706	total: 7.63s	remaining: 34.1s
183:	learn: 0.2790994	total: 7.68s	remaining: 34.1s
184:	learn: 0.2790577	total: 7.73s	remaining: 34.1s
185:	learn: 0.2789923	total: 7.79s	remaining: 34.1s
186:	learn: 0.2789150	total: 7.83s	remaining: 34.1s
187:	learn: 0.2788595	total: 7.88s	remaining: 34s
188:	learn: 0.2788224	total: 7.92s	remaining: 34s
189:	learn: 0.2787312	total: 7.97s	remaining: 34s
190:	learn: 0.2786839	total: 8.01s	remaining: 33.9s
191:	learn: 0.2786310	total: 8.05s	remaining: 33.9s
192:	learn: 0.2786162	total: 8.1s	remaining: 33.9s
193:	learn: 0.2785317	total: 8.14s	remaining: 33.8s
194:	learn: 0.2785050	total: 8.18s	remaining: 33.8s
195:	learn: 0.2785011	total: 8.22s	remaining: 33.7s
196:	learn: 0.2783290	total: 8.26s	remaining: 33.7s
197:	learn: 0.2782953	total: 8.31s	remaining: 33.6s
198:	learn: 0.2782477	total: 8.35s	remaining: 33.6s
199:	learn: 0.2781775	total: 8.39s	remaining: 33.6s
200:	learn: 0.2781116	total: 8.43s	remaining: 33.5s
201:	learn: 0.2780033	total: 8.48s	remaining: 33.5s
202:	learn: 0.2779979	total: 8.51s	remaining: 33.4s
203:	learn: 0.2779374	total: 8.55s	remaining: 33.4s
204:	learn: 0.2778947	total: 8.6s	remaining: 33.3s
205:	learn: 0.2778402	total: 8.64s	remaining: 33.3s
206:	learn: 0.2778027	total: 8.68s	remaining: 33.3s
207:	learn: 0.2777912	total: 8.72s	remaining: 33.2s
208:	learn: 0.2777162	total: 8.76s	remaining: 33.2s
209:	learn: 0.2776333	total: 8.81s	remaining: 33.1s
210:	learn: 0.2775552	total: 8.85s	remaining: 33.1s
211:	learn: 0.2773958	total: 8.9s	remaining: 33.1s
212:	learn: 0.2773178	total: 8.95s	remaining: 33.1s
213:	learn: 0.2772783	total: 9.01s	remaining: 33.1s
214:	learn: 0.2772553	total: 9.05s	remaining: 33.1s
215:	learn: 0.2772220	total: 9.11s	remaining: 33.1s
216:	learn: 0.2771568	total: 9.16s	remaining: 33s
217:	learn: 0.2770530	total: 9.21s	remaining: 33.1s
218:	learn: 0.2769828	total: 9.26s	remaining: 33s
219:	learn: 0.2769266	total: 9.3s	remaining: 33s
220:	learn: 0.2768421	total: 9.35s	remaining: 32.9s
221:	learn: 0.2767995	total: 9.39s	remaining: 32.9s
222:	learn: 0.2767796	total: 9.43s	remaining: 32.9s
223:	learn: 0.2767251	total: 9.47s	remaining: 32.8s
224:	learn: 0.2766108	total: 9.51s	remaining: 32.8s
225:	learn: 0.2766046	total: 9.55s	remaining: 32.7s
226:	learn: 0.2765216	total: 9.6s	remaining: 32.7s
227:	learn: 0.2764572	total: 9.64s	remaining: 32.6s
228:	learn: 0.2764373	total: 9.68s	remaining: 32.6s
229:	learn: 0.2764148	total: 9.72s	remaining: 32.5s
230:	learn: 0.2763663	total: 9.76s	remaining: 32.5s
231:	learn: 0.2763181	total: 9.8s	remaining: 32.5s
232:	learn: 0.2762816	total: 9.84s	remaining: 32.4s
233:	learn: 0.2762333	total: 9.89s	remaining: 32.4s
234:	learn: 0.2761983	total: 9.94s	remaining: 32.4s
235:	learn: 0.2761277	total: 10s	remaining: 32.4s
236:	learn: 0.2760625	total: 10.1s	remaining: 32.4s
237:	learn: 0.2760059	total: 10.1s	remaining: 32.4s
238:	learn: 0.2759469	total: 10.2s	remaining: 32.4s
239:	learn: 0.2758780	total: 10.2s	remaining: 32.4s
240:	learn: 0.2757453	total: 10.3s	remaining: 32.3s
241:	learn: 0.2757070	total: 10.3s	remaining: 32.3s
242:	learn: 0.2756214	total: 10.4s	remaining: 32.3s
243:	learn: 0.2755871	total: 10.4s	remaining: 32.2s
244:	learn: 0.2755530	total: 10.4s	remaining: 32.2s
245:	learn: 0.2754561	total: 10.5s	remaining: 32.1s
246:	learn: 0.2753774	total: 10.5s	remaining: 32.1s
247:	learn: 0.2753083	total: 10.6s	remaining: 32.1s
248:	learn: 0.2751669	total: 10.6s	remaining: 32.1s
249:	learn: 0.2750399	total: 10.7s	remaining: 32.1s
250:	learn: 0.2749746	total: 10.7s	remaining: 32.1s
251:	learn: 0.2749207	total: 10.8s	remaining: 32.1s
252:	learn: 0.2748284	total: 10.8s	remaining: 32s
253:	learn: 0.2747521	total: 10.9s	remaining: 32s
254:	learn: 0.2746889	total: 11s	remaining: 32s
255:	learn: 0.2745597	total: 11s	remaining: 32.1s
256:	learn: 0.2744827	total: 11.1s	remaining: 32s
257:	learn: 0.2744091	total: 11.1s	remaining: 32s
258:	learn: 0.2743783	total: 11.2s	remaining: 31.9s
259:	learn: 0.2742953	total: 11.2s	remaining: 31.9s
260:	learn: 0.2741807	total: 11.3s	remaining: 31.9s
261:	learn: 0.2741514	total: 11.3s	remaining: 31.9s
262:	learn: 0.2741411	total: 11.4s	remaining: 31.8s
263:	learn: 0.2740037	total: 11.4s	remaining: 31.8s
264:	learn: 0.2739285	total: 11.4s	remaining: 31.8s
265:	learn: 0.2738736	total: 11.5s	remaining: 31.7s
266:	learn: 0.2738325	total: 11.5s	remaining: 31.7s
267:	learn: 0.2737463	total: 11.6s	remaining: 31.6s
268:	learn: 0.2737463	total: 11.6s	remaining: 31.5s
269:	learn: 0.2737049	total: 11.6s	remaining: 31.5s
270:	learn: 0.2736290	total: 11.7s	remaining: 31.4s
271:	learn: 0.2735876	total: 11.7s	remaining: 31.4s
272:	learn: 0.2735668	total: 11.8s	remaining: 31.3s
273:	learn: 0.2734332	total: 11.8s	remaining: 31.3s
274:	learn: 0.2733641	total: 11.9s	remaining: 31.3s
275:	learn: 0.2733078	total: 11.9s	remaining: 31.3s
276:	learn: 0.2732245	total: 12s	remaining: 31.3s
277:	learn: 0.2731923	total: 12s	remaining: 31.2s
278:	learn: 0.2731534	total: 12.1s	remaining: 31.2s
279:	learn: 0.2731143	total: 12.1s	remaining: 31.1s
280:	learn: 0.2730511	total: 12.2s	remaining: 31.1s
281:	learn: 0.2729589	total: 12.2s	remaining: 31.1s
282:	learn: 0.2729145	total: 12.2s	remaining: 31s
283:	learn: 0.2727995	total: 12.3s	remaining: 31s
284:	learn: 0.2727081	total: 12.3s	remaining: 30.9s
285:	learn: 0.2726686	total: 12.4s	remaining: 30.9s
286:	learn: 0.2725893	total: 12.4s	remaining: 30.8s
287:	learn: 0.2725329	total: 12.5s	remaining: 30.8s
288:	learn: 0.2724494	total: 12.5s	remaining: 30.8s
289:	learn: 0.2723917	total: 12.6s	remaining: 30.8s
290:	learn: 0.2722852	total: 12.6s	remaining: 30.7s
291:	learn: 0.2721898	total: 12.6s	remaining: 30.7s
292:	learn: 0.2721330	total: 12.7s	remaining: 30.6s
293:	learn: 0.2720485	total: 12.7s	remaining: 30.6s
294:	learn: 0.2719970	total: 12.8s	remaining: 30.5s
295:	learn: 0.2719500	total: 12.8s	remaining: 30.5s
296:	learn: 0.2718440	total: 12.9s	remaining: 30.6s
297:	learn: 0.2717968	total: 13s	remaining: 30.5s
298:	learn: 0.2717666	total: 13s	remaining: 30.5s
299:	learn: 0.2716413	total: 13.1s	remaining: 30.5s
300:	learn: 0.2716091	total: 13.1s	remaining: 30.4s
301:	learn: 0.2715663	total: 13.1s	remaining: 30.4s
302:	learn: 0.2715476	total: 13.2s	remaining: 30.3s
303:	learn: 0.2714644	total: 13.2s	remaining: 30.3s
304:	learn: 0.2714054	total: 13.3s	remaining: 30.3s
305:	learn: 0.2713531	total: 13.3s	remaining: 30.2s
306:	learn: 0.2713131	total: 13.4s	remaining: 30.2s
307:	learn: 0.2712201	total: 13.4s	remaining: 30.2s
308:	learn: 0.2711642	total: 13.5s	remaining: 30.1s
309:	learn: 0.2711362	total: 13.5s	remaining: 30.1s
310:	learn: 0.2710828	total: 13.6s	remaining: 30s
311:	learn: 0.2710059	total: 13.6s	remaining: 30s
312:	learn: 0.2709078	total: 13.7s	remaining: 30s
313:	learn: 0.2708104	total: 13.7s	remaining: 30s
314:	learn: 0.2707920	total: 13.8s	remaining: 29.9s
315:	learn: 0.2706753	total: 13.8s	remaining: 29.9s
316:	learn: 0.2706080	total: 13.8s	remaining: 29.8s
317:	learn: 0.2705319	total: 13.9s	remaining: 29.8s
318:	learn: 0.2704840	total: 13.9s	remaining: 29.8s
319:	learn: 0.2704137	total: 14s	remaining: 29.7s
320:	learn: 0.2703853	total: 14s	remaining: 29.7s
321:	learn: 0.2703115	total: 14.1s	remaining: 29.6s
322:	learn: 0.2702783	total: 14.1s	remaining: 29.6s
323:	learn: 0.2702139	total: 14.2s	remaining: 29.5s
324:	learn: 0.2701296	total: 14.2s	remaining: 29.5s
325:	learn: 0.2701078	total: 14.2s	remaining: 29.5s
326:	learn: 0.2700514	total: 14.3s	remaining: 29.4s
327:	learn: 0.2699844	total: 14.3s	remaining: 29.4s
328:	learn: 0.2699367	total: 14.4s	remaining: 29.4s
329:	learn: 0.2699056	total: 14.4s	remaining: 29.3s
330:	learn: 0.2698040	total: 14.5s	remaining: 29.3s
331:	learn: 0.2697690	total: 14.5s	remaining: 29.2s
332:	learn: 0.2696344	total: 14.6s	remaining: 29.2s
333:	learn: 0.2695395	total: 14.6s	remaining: 29.1s
334:	learn: 0.2695083	total: 14.7s	remaining: 29.1s
335:	learn: 0.2693480	total: 14.7s	remaining: 29.1s
336:	learn: 0.2692705	total: 14.7s	remaining: 29s
337:	learn: 0.2692117	total: 14.8s	remaining: 29s
338:	learn: 0.2691482	total: 14.8s	remaining: 28.9s
339:	learn: 0.2690806	total: 14.9s	remaining: 28.9s
340:	learn: 0.2690095	total: 14.9s	remaining: 28.9s
341:	learn: 0.2689632	total: 15s	remaining: 28.8s
342:	learn: 0.2689438	total: 15s	remaining: 28.8s
343:	learn: 0.2688872	total: 15.1s	remaining: 28.7s
344:	learn: 0.2688055	total: 15.1s	remaining: 28.7s
345:	learn: 0.2686983	total: 15.2s	remaining: 28.7s
346:	learn: 0.2686772	total: 15.2s	remaining: 28.6s
347:	learn: 0.2686033	total: 15.3s	remaining: 28.6s
348:	learn: 0.2685113	total: 15.3s	remaining: 28.5s
349:	learn: 0.2684268	total: 15.3s	remaining: 28.5s
350:	learn: 0.2684039	total: 15.4s	remaining: 28.4s
351:	learn: 0.2683848	total: 15.4s	remaining: 28.4s
352:	learn: 0.2683294	total: 15.5s	remaining: 28.3s
353:	learn: 0.2682986	total: 15.5s	remaining: 28.3s
354:	learn: 0.2681776	total: 15.6s	remaining: 28.3s
355:	learn: 0.2680777	total: 15.6s	remaining: 28.2s
356:	learn: 0.2680274	total: 15.6s	remaining: 28.2s
357:	learn: 0.2679737	total: 15.7s	remaining: 28.1s
358:	learn: 0.2679461	total: 15.7s	remaining: 28.1s
359:	learn: 0.2678574	total: 15.8s	remaining: 28s
360:	learn: 0.2678219	total: 15.8s	remaining: 28s
361:	learn: 0.2677895	total: 15.9s	remaining: 27.9s
362:	learn: 0.2677603	total: 15.9s	remaining: 27.9s
363:	learn: 0.2677202	total: 15.9s	remaining: 27.8s
364:	learn: 0.2676373	total: 16s	remaining: 27.8s
365:	learn: 0.2676274	total: 16s	remaining: 27.8s
366:	learn: 0.2676098	total: 16.1s	remaining: 27.7s
367:	learn: 0.2675202	total: 16.1s	remaining: 27.7s
368:	learn: 0.2674710	total: 16.1s	remaining: 27.6s
369:	learn: 0.2672956	total: 16.2s	remaining: 27.6s
370:	learn: 0.2672189	total: 16.2s	remaining: 27.5s
371:	learn: 0.2671664	total: 16.3s	remaining: 27.5s
372:	learn: 0.2670821	total: 16.3s	remaining: 27.4s
373:	learn: 0.2670064	total: 16.4s	remaining: 27.4s
374:	learn: 0.2669480	total: 16.4s	remaining: 27.3s
375:	learn: 0.2668923	total: 16.5s	remaining: 27.3s
376:	learn: 0.2667691	total: 16.5s	remaining: 27.3s
377:	learn: 0.2667017	total: 16.5s	remaining: 27.2s
378:	learn: 0.2666124	total: 16.6s	remaining: 27.2s
379:	learn: 0.2665860	total: 16.6s	remaining: 27.1s
380:	learn: 0.2665529	total: 16.7s	remaining: 27.1s
381:	learn: 0.2664821	total: 16.7s	remaining: 27.1s
382:	learn: 0.2664646	total: 16.8s	remaining: 27s
383:	learn: 0.2664048	total: 16.8s	remaining: 27s
384:	learn: 0.2663522	total: 16.9s	remaining: 26.9s
385:	learn: 0.2662729	total: 16.9s	remaining: 26.9s
386:	learn: 0.2662321	total: 16.9s	remaining: 26.8s
387:	learn: 0.2661652	total: 17s	remaining: 26.8s

In [34]:
cat_boost_gini = gini_score(y_valid, model_CatBoost.predict_proba(X_valid)[:,1])

print(f'Gini score for CatBoost:  {cat_boost_gini}')

Gini score for CatBoost:  0.48921298668817137

## LightGBM

Главная особенность метода в том, что самый быстрый по сравнению с другими. Очень эффективный для больших данных и нетребовательный к ресурсам. Больше всего времени в алгоритмах бустинга занимает построение деревьев, поэтому в LightGBM решили строить деревья быстрее, за счёт другой структры, уменьшения количества наблюдений и уменьшения количества признаков, по которым ищется критерий разделения.

- построение деревьев происходит по листам, то есть ищет лучшее рабиение в листе, из-за чего деревья могут получаться несимметричными и глубокими. Однако такой метод построения гораздо быстрее остальных.
- выбираются наблюдения с большим градиентом, так как они сильнее влияют, а с маленьким градиентом наблюдения не сильно помогут в обучении, зато заметно повысится скорость обучения. Отбор наблюдений происходит при помощи метода GOSS
- при помощи метода EFB вместо k-признаков строят p-связок, пирчём p <= k. Данный алгоритм строить связки таким образом, чтобы вделить важные связанные признаки, чтобы не потерять в качестве модели. И так как таких связок меньше, чем признаков, обучение можели происходит быстрее.
- linear_tree - будут использвоаться не обычные деревья, где ответы в листьях константы, а ответом будет линейная модель на основе признаков.

In [35]:
lightGBM_model = LGBMClassifier(random_state=21, n_jobs=-1, linear_tree=True, learning_rate=0.01)
lightGBM_model.fit(X_train_transform, y_train)

[LightGBM] [Info] Number of positive: 2794, number of negative: 21533
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000923 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3646
[LightGBM] [Info] Number of data points in the train set: 24327, number of used features: 67
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.114852 -> initscore=-2.042112
[LightGBM] [Info] Start training from score -2.042112

LGBMClassifier(learning_rate=0.01, linear_tree=True, n_jobs=-1, random_state=21)

In [36]:
lightGBM_gini = gini_score(y_valid, lightGBM_model.predict_proba(X_valid_transform)[:,1])

print(f'Gini score for LightGBM model:  {lightGBM_gini}')

Gini score for LightGBM model:  0.46082956632788563

c:\Users\User\anaconda3\envs\ml_projects\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

## XGBoost

- основное отличие - это втроенная регуляризация в функию ошибок. Штраф за сложность дерева. Регуляризация весов в лситьях и l1, l2 регуляризцая. Позволяет бороться в переобучением и снижать его риск.
- при поиске разделений, перебираются не все возможные уникальные значения, а происходит разбиение по квантилям, и уже по кванитлям ищется разделение.
- автоматичеки обрабатывает пропущенные занчеия.
- деревья строятся по уровням, то есть дерево будет симметричным, однако на одном уровне в узлах могут быть различные критерии разделения
- DART - специльнай режим, при котором при добавлении нового дерева происходит случайное удаление ранее обученных деревьев. При обучении, послдение деревья теряют обощающие способности, и подстраиваются уже под конкретные примеры. Удаление некторых деревеьев позвоаляет созранять обощающие способности.

In [37]:
xgb_model = XGBClassifier(max_depth=3, booster='dart', n_jobs=-1, random_state=21, n_estimators=100)
xgb_model.fit(X_train_transform, y_train)

XGBClassifier(base_score=None, booster='dart', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=-1, num_parallel_tree=None, ...)

In [38]:
xgb_gini = gini_score(y_valid, xgb_model.predict_proba(X_valid_transform)[:,1])

print(f'Gini score for XGBoost:  {xgb_gini}')

Gini score for XGBoost:  0.47356877841834355

## Сравнение и выводы по всем 3 моделям

In [39]:
print(f'Gini score for CatBoost:  {cat_boost_gini}')
print(f'Gini score for XGBoost:  {xgb_gini}')
print(f'Gini score for LightGBM model:  {lightGBM_gini}')

Gini score for CatBoost:  0.48921298668817137
Gini score for XGBoost:  0.47356877841834355
Gini score for LightGBM model:  0.46082956632788563

Модель CatBoost даёт лучшие значения метрики. Связано это с тем, что:
- при обучении подавались данные исходные X_train, в которых оставались категорильные признаки, которые модель сама кодировала. Для остальных же моделей использовались X_train_tranform, и возможно обработка категорильаных признаков в CatBoost лучше, чем моя обработка, вследствии чего значения лучше.
- CatBoost также сам выбирал значения learning_rate при помощи своих эвристик, когда в случае в остлаьными моделями приходилось подбирать самому. Возможно при более тщательном подборе гиперпаметров, другие модели могли бы показать лучшие значение метрик. То есть для дургих моделей возможно нужна более тонкая настройка гиперпарамтеров.

# 8. Take the best model and estimate its performance on the test dataset.

Is your model overfitting or not? Explain.

### Лучшее значение получилось у CatBoost

In [40]:
cat_boost_gini_train = gini_score(y_train, model_CatBoost.predict_proba(X_train)[:,1])
cat_boost_gini_valid = gini_score(y_valid, model_CatBoost.predict_proba(X_valid)[:,1])
cat_boost_gini_test = gini_score(y_test, model_CatBoost.predict_proba(X_test)[:,1])

print(f'CatBoost Gini score:')
print(f'Train:  {cat_boost_gini_train}')
print(f'Valid:  {cat_boost_gini_valid}')
print(f'Test:  {cat_boost_gini_test}')

CatBoost Gini score:
Train:  0.6941217490385567
Valid:  0.48921298668817137
Test:  0.4983360279430875

Можем видеть, что значения Gini на тестовой выборке даже выше, чем на валидационной. Это гооворит о том, что модель не переобучилась и дотстаочно хорошо работате на незнакомых данных, на которых смотрим метрику только сейчас.

# 9*. Bonus part. Implementj the ExtraTreesClassifier  and check its performance. 

You must improve the result of a single tree and obtain a Gini score of at least 0.12 on the validation dataset.

ExtraTreesClassifier - это как randomForest, только мы не передаем подвыборку, я передаём все данные, но при этом деревья не обычные, а ExtraRandomizeTree, в котором мы не перебираем уникальные значения или квантили, а берём n рандомно различных значений и среди них ищем лучшее разделение

In [41]:
class myExtraTreesClassifier:
    def __init__(self, n_estimators=100, random_state=21, max_depth=15, max_features='sqrt'):
        self.n_estimators = n_estimators
        self.random_state = random_state
        self.max_depth = max_depth
        self.max_features = max_features
        self.trees = []
    
    def fit(self, X, y):
        if self.max_features == 'sqrt':
            max_features = int(np.sqrt(X.shape[1]))
        else:
            raise ValueError(f'Unknown value of parameter max_features:  {self.max_features}???')
        
        tree_random_state = self.random_state
        
        for i in tqdm(range(self.n_estimators), desc=f'Fitting  forest'):

            tree = myExtraRandomizedTree(max_depth=self.max_depth, max_features=max_features, random_state=tree_random_state)
            tree_random_state += 1
    
            tree.fit(X, y)

            self.trees.append(tree)
    
    def predict_proba(self, X):
        votes = [tree.predict_proba(X) for tree in self.trees]

        return np.mean(votes, axis=0)
    
    def predict(self, X, threshold=0.5):
        predictions = (self.predict_proba(X) > threshold).astype(int)

        return np.array(predictions)

In [42]:
my_ExtraTrees = myExtraTreesClassifier(n_estimators=50, max_depth=10)
my_ExtraTrees.fit(X_train_transform, y_train)

Fitting  forest: 100%|██████████| 50/50 [01:03<00:00,  1.27s/it]

In [43]:
my_ExtraTrees_gini = gini_score(y_valid, my_ExtraTrees.predict_proba(X_valid_transform))

print(f'Gini score for my ExtraTreesClassifier:  {my_ExtraTrees_gini}')

Gini score for my ExtraTreesClassifier:  0.44523931112390924

In [44]:
print(f'Gini score for my RandomForestClassifier:  {forest_gini_}')

Gini score for my RandomForestClassifier:  0.4554602354851165

Значений немного хуже, однако значения выбирались ранодмно, а не перебом. Хотя в мое реализации есть ограничени, и перебор идёт по квантилям, но если сравнивать с классичсеким подходом, то ExtraTrees очень хорошо справляется с задачей и существенно быстрее прямого перебора. 
* Плюсы:
    - такой подход с рандомных поиском раздееления позволяет бороться с переобучением. 
    - Также данный метод быстрее классического, что весьма важно на больших наборах данных. 
    - лучше обобщает данные, устойчивее к выборсам и шуму в данных.
- Минусы
    - меньшая точность, так как случаные пороги могут пропустить оптимальное разделение
    - требует больше деревьев для достижения той же точности, что и RandomForest
    - сложнее интерпретировать