# Day 09. Exercise 02
# Metrics

## 0. Imports

In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import precision_score, recall_score, roc_auc_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import  joblib

## 1. Preprocessing

1. Create the same dataframe as in the previous exercise.
2. Using `train_test_split` with parameters `test_size=0.2`, `random_state=21` get `X_train`, `y_train`, `X_test`, `y_test`. Use the additional parameter `stratify`.

In [27]:
df = pd.read_csv('../data/day-of-week-not-scaled.csv')
df

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [28]:
dayofweek = pd.read_csv('../data/dayofweek.csv')
df['dayofweek'] = dayofweek.dayofweek
del dayofweek

In [29]:
X = df.drop(columns=['dayofweek'])
y = df.dayofweek

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=21, test_size=0.2, stratify=y)

## 2. SVM

1. Use the best parameters from the previous exercise and train the model of SVM.
2. You need to calculate `accuracy`, `precision`, `recall`, `ROC AUC`.

 - `precision` and `recall` should be calculated for each class (use `average='weighted'`)
 - `ROC AUC` should be calculated for each class against any other class (all possible pairwise combinations) and then weighted average should be applied for the final metric
 - the code in the cell should display the result as below:

```
accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878
```

In [31]:
svc_model = SVC(random_state=21, C=10, gamma='auto', kernel='rbf', probability=True)
svc_model.fit(X_train, y_train)
predict = svc_model.predict(X_test)
predict_proba = svc_model.predict_proba(X_test)

In [32]:
print(f'accuracy is {svc_model.score(X_test, y_test):.5f}')
print(f'precision is {precision_score(y_test, predict, average='weighted'):.5f}')
print(f'recall is {recall_score(y_test, predict, average='weighted'):.5f}')
print(f'roc_auc is {roc_auc_score(y_test, predict_proba, multi_class='ovo', average='weighted'):.5f}')

accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878

## 3. Decision tree

1. The same task for decision tree

In [33]:
tree_model = DecisionTreeClassifier(random_state=21, class_weight='balanced', criterion='gini', max_depth=21)
tree_model.fit(X_train, y_train)
tree_predict = tree_model.predict(X_test)
tree_predict_proba = tree_model.predict_proba(X_test)

In [34]:
print(f'accuracy is {tree_model.score(X_test, y_test):.5f}')
print(f'precision is {precision_score(y_test, tree_predict, average='weighted'):.5f}')
print(f'recall is {recall_score(y_test, tree_predict, average='weighted'):.5f}')
print(f'roc_auc is {roc_auc_score(y_test, tree_predict_proba, multi_class='ovo', average='weighted'):.5f}')

accuracy is 0.89053
precision is 0.89402
recall is 0.89053
roc_auc is 0.93793

## 4. Random forest

1. The same task for random forest.

In [35]:
forest_model = RandomForestClassifier(class_weight='balanced', criterion='entropy', max_depth=24, n_estimators=100, random_state=21)
forest_model.fit(X_train, y_train)
forest_predict = forest_model.predict(X_test)
forest_predict_proba= forest_model.predict_proba(X_test)

In [36]:
print(f'accuracy is {forest_model.score(X_test, y_test):.5f}')
print(f'precision is {precision_score(y_test, forest_predict, average='weighted'):.5f}')
print(f'recall is {recall_score(y_test, forest_predict, average='weighted'):.5f}')
print(f'roc_auc is {roc_auc_score(y_test, forest_predict_proba, multi_class='ovo', average='weighted'):.5f}')

accuracy is 0.93195
precision is 0.93402
recall is 0.93195
roc_auc is 0.98821

## 5. Predictions

1. Choose the best model.
2. Analyze: for which `weekday` your model makes the most errors (in % of the total number of samples of that class in your full dataset), for which `labname` and for which `users`.
3. Save the model.

In [37]:
predict_all_dataset = forest_model.predict(X)
predict_all_dataset

array([4., 4., 4., ..., 3., 3., 3.])

In [38]:
df['predict'] = predict_all_dataset
df['is_different_result'] = df.dayofweek != df.predict
df.head()

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek,predict,is_different_result
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,False
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,False
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,False
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,False
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,4.0,False

In [39]:
number_dayofweek = dict(df.dayofweek.value_counts())

In [40]:
error = df[df['is_different_result'] == True]
error.head()

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1,dayofweek,predict,is_different_result
43,7,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,6.0,True
46,8,21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,5.0,6.0,True
74,7,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,True
98,8,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,True
101,1,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,True

## which day of week

In [41]:
weekday_error = pd.DataFrame(error.groupby(['dayofweek'])['is_different_result'].count()).reset_index()
weekday_error['all_numbers'] = [number_dayofweek[x] for x in range(0,7)]
weekday_error['percent_error'] = weekday_error.is_different_result / weekday_error.all_numbers
weekday_error

   dayofweek  is_different_result  all_numbers  percent_error
0        0.0                    6          136       0.044118
1        1.0                    3          274       0.010949
2        2.0                    2          149       0.013423
3        3.0                    2          396       0.005051
4        4.0                    3          104       0.028846
5        5.0                    5          271       0.018450
6        6.0                    2          356       0.005618

In [42]:
print(f'max error of weekday is {weekday_error.idxmax()['percent_error']}')

max error of weekday is 0

## which labname

In [43]:
lab_list = [i for i in df.columns if i.startswith('labname')]
lab_list

['labname_code_rvw',
 'labname_lab02',
 'labname_lab03',
 'labname_lab03s',
 'labname_lab05s',
 'labname_laba04',
 'labname_laba04s',
 'labname_laba05',
 'labname_laba06',
 'labname_laba06s',
 'labname_project1']

In [44]:
max_lab_error = 0
max_lab = ''
for lab in lab_list:
    error_perc = error[lab].sum() / len(predict_all_dataset)
    if error_perc > max_lab_error:
        max_lab_error = error_perc
        max_lab = lab

print(f'max lab error: {max_lab}, error percent: {max_lab_error * 100}%')

max lab error: labname_project1, error percent: 0.5338078291814947%

## which user

In [45]:
uid_list = [i for i in df.columns if i.startswith('uid')]
uid_list

['uid_user_0',
 'uid_user_1',
 'uid_user_10',
 'uid_user_11',
 'uid_user_12',
 'uid_user_13',
 'uid_user_14',
 'uid_user_15',
 'uid_user_16',
 'uid_user_17',
 'uid_user_18',
 'uid_user_19',
 'uid_user_2',
 'uid_user_20',
 'uid_user_21',
 'uid_user_22',
 'uid_user_23',
 'uid_user_24',
 'uid_user_25',
 'uid_user_26',
 'uid_user_27',
 'uid_user_28',
 'uid_user_29',
 'uid_user_3',
 'uid_user_30',
 'uid_user_31',
 'uid_user_4',
 'uid_user_6',
 'uid_user_7',
 'uid_user_8']

In [46]:
max_uid_error = 0
max_uid = ''
for uid in uid_list:
    error_perc = error[uid].sum() / len(predict_all_dataset)
    if error_perc > max_uid_error:
        max_uid_error = error_perc
        max_uid = uid

print(f'max uid error: {max_uid}, error percent: {max_uid_error * 100}%')

max uid error: uid_user_2, error percent: 0.1779359430604982%

In [47]:
joblib.dump(forest_model, 'random_forest_model.joblib')

['random_forest_model.joblib']

## 6. Function

1. Write a function that takes a list of different models and a corresponding list of parameters (dicts) and returns a dict that contains all the 4 metrics for each model.

In [ ]:
def calculate_metrics(models_list, params_list):
    answer = []

    for i in range(len(models_list)):
        model = models_list[i].set_params(**params_list[i])
        model.fit(X_train, y_train)
        predict = model.predict(X_test)
        predict_proba = model.predict_proba(X_test)

        d = {'accuracy' : model.score(X_test, y_test),
             'precision' : precision_score(y_test, predict, average='weighted'),
             'recall' : recall_score(y_test, predict, average='weighted'),
             'roc_auc' : roc_auc_score(y_test, predict_proba, multi_class='ovo', average='weighted')}
        answer.append(d)
    
    return answer

In [49]:
models = [
    RandomForestClassifier(),
    SVC(probability=True)
]
param_grids = [
    {'n_estimators': 100, 'max_depth': 24, 'random_state': 21, 'class_weight': 'balanced', 'criterion' : 'entropy'},
    {'C': 10, 'kernel': 'rbf', 'gamma': 'auto', 'random_state' : 21}
]

In [50]:
calculate_metrics(models, param_grids)

[{'accuracy': 0.9319526627218935,
  'precision': 0.9340183677910212,
  'recall': 0.9319526627218935,
  'roc_auc': 0.9882077759075321},
 {'accuracy': 0.8875739644970414,
  'precision': 0.8926729169690374,
  'recall': 0.8875739644970414,
  'roc_auc': 0.9787793228216216}]